// Generated by scripts/sync-workspace.mjs from lib/industrial-links.ts.
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.industrialLinks = industrialLinks;
exports.configureIndustrialLink = configureIndustrialLink;
exports.syncPublishedPoints = syncPublishedPoints;
const db_1 = require("./db");
const permissions_1 = require("./permissions");
const stock_ledger_1 = require("./stock-ledger");
async function industrialLinks(user) {
    (0, permissions_1.demand)(user, "people");
    const c = (0, db_1.getPool)();
    const [branches, blocks, sectors, workplaces, points, users, warehouses, pending] = await Promise.all([
        (0, stock_ledger_1.rows)(c, "SELECT * FROM branches ORDER BY code"), (0, stock_ledger_1.rows)(c, "SELECT * FROM blocks ORDER BY code"), (0, stock_ledger_1.rows)(c, "SELECT * FROM sectors ORDER BY code"), (0, stock_ledger_1.rows)(c, "SELECT * FROM workplaces ORDER BY code"), (0, stock_ledger_1.rows)(c, "SELECT * FROM plant_points WHERE active=TRUE ORDER BY label"),
        (0, stock_ledger_1.rows)(c, "SELECT id,employee_no,name,block_id,branch_id,sector_id,workplace_id FROM users WHERE active=TRUE ORDER BY employee_no"), (0, stock_ledger_1.rows)(c, "SELECT id,code,name,block_id,branch_id FROM warehouses WHERE active=TRUE ORDER BY code"),
        (0, stock_ledger_1.rows)(c, "SELECT p.code,w.name AS warehouse,i.map_node_id FROM inventory i JOIN parts p ON p.id=i.part_id JOIN warehouses w ON w.id=i.warehouse_id LEFT JOIN plant_points pt ON pt.id=i.map_node_id WHERE i.map_node_id IS NULL OR pt.id IS NULL OR pt.active=FALSE ORDER BY p.code,w.name LIMIT 200"),
    ]);
    return { branches, blocks, sectors, workplaces, points, users, warehouses, pending, basis: "Vínculos explícitos por IDs. Cadastros históricos sem vínculo exigem configuração; nomes não determinam localização." };
}
async function configureIndustrialLink(user, a) {
    (0, permissions_1.demand)(user, "people");
    return (0, db_1.transaction)(async (c) => {
        const actor = await (0, stock_ledger_1.first)(c, "SELECT id FROM users WHERE employee_no=? AND active=TRUE FOR UPDATE", [user.id]);
        if (!actor)
            throw new permissions_1.ActionError("Sessão inválida.", 401);
        let id;
        if (a.type === "branch") {
            const code = (0, permissions_1.text)(a.code, 64), name = (0, permissions_1.text)(a.name, 160) || null;
            if (!code)
                throw new permissions_1.ActionError("Informe o código textual da filial.");
            const r = await (0, stock_ledger_1.insert)(c, "INSERT INTO branches(code,name) VALUES(?,?) RETURNING id", [code, name]);
            id = Number(r.id);
        }
        else if (a.type === "blockBranch" || a.type === "warehouseBranch") {
            id = (0, permissions_1.integer)(a.id);
            const branchId = (0, permissions_1.integer)(a.branchId), table = a.type === "blockBranch" ? "blocks" : "warehouses";
            if (!await (0, stock_ledger_1.first)(c, "SELECT id FROM branches WHERE id=?", [branchId]) || !await (0, stock_ledger_1.first)(c, `SELECT id FROM ${table} WHERE id=? FOR UPDATE`, [id]))
                throw new permissions_1.ActionError("Filial ou cadastro inexistente.", 404);
            const dependents = await (0, stock_ledger_1.first)(c, table === "blocks" ? "SELECT id FROM sectors WHERE block_id=? AND branch_id<>? LIMIT 1" : "SELECT id FROM inventory i JOIN reported_balances r ON r.warehouse_id=i.warehouse_id WHERE i.warehouse_id=? AND r.branch_id<>? LIMIT 1", [id, branchId]);
            if (dependents)
                throw new permissions_1.ActionError("Existem vínculos incompatíveis; revise-os antes de alterar a filial.", 409);
            await c.execute(`UPDATE ${table} SET branch_id=? WHERE id=?`, [branchId, id]);
        }
        else if (a.type === "sector") {
            const branchId = (0, permissions_1.integer)(a.branchId), blockId = (0, permissions_1.integer)(a.blockId), code = (0, permissions_1.text)(a.code, 64), name = (0, permissions_1.text)(a.name, 160);
            if (!code || !name)
                throw new permissions_1.ActionError("Informe código e nome oficiais do setor.");
            if (!await (0, stock_ledger_1.first)(c, "SELECT id FROM blocks WHERE id=? AND branch_id=?", [blockId, branchId]))
                throw new permissions_1.ActionError("Vincule o bloco à filial antes de cadastrar o setor.", 409);
            const r = await (0, stock_ledger_1.insert)(c, "INSERT INTO sectors(code,name,branch_id,block_id) VALUES(?,?,?,?) RETURNING id", [code, name, branchId, blockId]);
            id = Number(r.id);
        }
        else if (a.type === "workplace") {
            const sectorId = (0, permissions_1.integer)(a.sectorId), code = (0, permissions_1.text)(a.code, 64), name = (0, permissions_1.text)(a.name, 160), point = (0, permissions_1.text)(a.pointId, 64) || null;
            if (!code || !name)
                throw new permissions_1.ActionError("Informe código e nome oficiais do local de trabalho.");
            const sector = await (0, stock_ledger_1.first)(c, "SELECT * FROM sectors WHERE id=?", [sectorId]);
            if (!sector)
                throw new permissions_1.ActionError("Setor inexistente.", 404);
            if (point && !await (0, stock_ledger_1.first)(c, "SELECT id FROM plant_points WHERE id=? AND active=TRUE AND block_id=? AND (sector_id IS NULL OR sector_id=?)", [point, sector.block_id, sector.id]))
                throw new permissions_1.ActionError("Selecione um ponto publicado do bloco/setor autorizado.", 409);
            const r = await (0, stock_ledger_1.insert)(c, "INSERT INTO workplaces(code,name,branch_id,block_id,sector_id,point_id) VALUES(?,?,?,?,?,?) RETURNING id", [code, name, sector.branch_id, sector.block_id, sector.id, point]);
            id = Number(r.id);
        }
        else if (a.type === "userWorkplace") {
            id = (0, permissions_1.integer)(a.id);
            const workplace = await (0, stock_ledger_1.first)(c, "SELECT wp.*,s.name AS sector FROM workplaces wp JOIN sectors s ON s.id=wp.sector_id WHERE wp.id=?", [(0, permissions_1.integer)(a.workplaceId)]);
            if (!workplace || !await (0, stock_ledger_1.first)(c, "SELECT id FROM users WHERE id=? FOR UPDATE", [id]))
                throw new permissions_1.ActionError("Usuário ou local inexistente.", 404);
            await c.execute("UPDATE users SET workplace_id=?,sector_id=?,sector=?,branch_id=?,block_id=? WHERE id=?", [workplace.id, workplace.sector_id, workplace.sector, workplace.branch_id, workplace.block_id, id]);
        }
        else
            throw new permissions_1.ActionError("Vínculo inválido.");
        await (0, stock_ledger_1.audit)(c, Number(actor.id), "industrial_link", id, String(a.type), a);
        return { id };
    });
}
async function syncPublishedPoints(c, graph, version) {
    const linked = await (0, stock_ledger_1.rows)(c, "SELECT wp.code,wp.point_id,wp.block_id,wp.sector_id FROM workplaces wp WHERE wp.point_id IS NOT NULL");
    for (const wp of linked)
        if (!graph.nodes.some(n => n.id === wp.point_id && n.blockId === Number(wp.block_id) && (!n.sectorId || n.sectorId === Number(wp.sector_id))))
            throw new permissions_1.ActionError(`O local ${wp.code} perderia seu ponto vinculado. Revise o cadastro antes de publicar.`, 409);
    await c.execute("UPDATE plant_points SET active=FALSE WHERE active=TRUE");
    for (const n of graph.nodes) {
        if (n.sectorId && !await (0, stock_ledger_1.first)(c, "SELECT id FROM sectors WHERE id=? AND block_id=?", [n.sectorId, n.blockId ?? null]))
            throw new permissions_1.ActionError("Setor do ponto não pertence ao bloco selecionado.", 409);
        await c.execute("INSERT INTO plant_points(id,label,kind,warehouse_id,block_id,sector_id,published_version_id,active) VALUES(?,?,?,?,?,?,?,1) ON CONFLICT(id) DO UPDATE SET label=EXCLUDED.label,kind=EXCLUDED.kind,warehouse_id=EXCLUDED.warehouse_id,block_id=EXCLUDED.block_id,sector_id=EXCLUDED.sector_id,published_version_id=EXCLUDED.published_version_id,active=TRUE", [n.id, n.label, n.kind, n.warehouseId ?? null, n.blockId ?? null, n.sectorId ?? null, version]);
    }
}
