// Generated by scripts/sync-workspace.mjs from lib/permissions.ts.
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.can = exports.permissions = exports.ActionError = void 0;
exports.permitted = permitted;
exports.demand = demand;
exports.integer = integer;
exports.text = text;
exports.reason = reason;
class ActionError extends Error {
    status;
    constructor(message, status = 400) {
        super(message);
        this.status = status;
    }
}
exports.ActionError = ActionError;
exports.permissions = {
    admin: ["approve", "stock", "people", "map", "planning", "history"],
    lider: ["approve", "history"],
    almoxarifado: ["stock", "planning", "history"],
    funcionario: ["request", "history"],
};
const can = (role, permission) => exports.permissions[role].includes(permission);
exports.can = can;
const aliases = {
    request: ["requests.create"], approve: ["requests.approve"], stock: ["stock.manage"],
    people: ["users.manage"], map: [], planning: ["stock.manage"], history: [],
};
function permitted(user, permission, actionPermission) {
    return (0, exports.can)(user.role, permission) && ![permission, ...(actionPermission ? [actionPermission] : aliases[permission])].some((p) => user.permissionOverrides?.[p] === false);
}
function demand(user, permission, actionPermission) {
    if (!permitted(user, permission, actionPermission))
        throw new ActionError("Perfil sem permissão para esta ação.", 403);
}
function integer(value, min = 1) {
    if (typeof value !== "number" ||
        !Number.isSafeInteger(value) ||
        value < min ||
        value > 1_000_000_000)
        throw new ActionError("Quantidade inválida.");
    return value;
}
function text(value, max = 1000) {
    return typeof value === "string" ? value.trim().slice(0, max) : "";
}
function reason(value) {
    const result = text(value);
    if (result.length < 3)
        throw new ActionError("Informe uma justificativa com pelo menos 3 caracteres.");
    return result;
}
