// Generated by scripts/sync-workspace.mjs from lib/request-policy.ts.
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.requestPattern = requestPattern;
exports.requestAnomaly = requestAnomaly;
exports.requestedUnits = requestedUnits;
const median = (values) => {
    const sorted = [...values].sort((a, b) => a - b);
    const middle = Math.floor(sorted.length / 2);
    return sorted.length % 2
        ? sorted[middle]
        : (sorted[middle - 1] + sorted[middle]) / 2;
};
function requestPattern(history, partId, blockId, sector) {
    const sample = (matches) => ({
        total: matches.length,
        quantities: matches
            .filter((r) => Number(r.part_id) === partId)
            .map((r) => Number(r.quantity)),
    });
    return {
        block: sample(history.filter((r) => Number(r.block_id) === blockId)),
        sector: sample(history.filter((r) => r.sector === sector)),
    };
}
function requestAnomaly(quantity, pattern) {
    const reasons = [];
    let historySufficient = false;
    for (const [label, sample] of [
        ["bloco", pattern?.block],
        ["setor", pattern?.sector],
    ]) {
        if (!sample || sample.total < 5)
            continue;
        historySufficient = true;
        if (!sample.quantities.length)
            reasons.push(`Peça incomum no ${label}: nenhum pedido aprovado deste material nos últimos 90 dias.`);
        else if (sample.quantities.length >= 3) {
            const typical = median(sample.quantities);
            const deviation = median(sample.quantities.map((q) => Math.abs(q - typical)));
            const limit = Math.max(typical * 2, typical + 3 * Math.max(1, deviation));
            if (quantity > limit)
                reasons.push(`Quantidade incomum no ${label}: ${quantity}, acima do limite histórico de ${Math.floor(limit)} (mediana ${typical}).`);
        }
    }
    return { unusual: reasons.length > 0, reasons, historySufficient };
}
function requestedUnits(amount, unit, packSize) {
    if (!Number.isSafeInteger(amount) ||
        amount < 1 ||
        ![undefined, "piece", "box"].includes(unit))
        throw new Error("Quantidade ou unidade de requisição inválida.");
    const units = amount * (unit === "box" ? packSize : 1);
    if (!Number.isSafeInteger(units) || units < 1 || units > 1_000_000_000)
        throw new Error("Quantidade convertida inválida.");
    return units;
}
