// Generated by scripts/sync-workspace.mjs from lib/request-actions.ts.
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.requestActions = void 0;
exports.executeRequestAction = executeRequestAction;
const node_crypto_1 = require("node:crypto");
const delivery_planning_1 = require("./delivery-planning");
const permissions_1 = require("./permissions");
const stock_ledger_1 = require("./stock-ledger");
const routing_1 = require("./routing");
exports.requestActions = new Set([
    "createRequests",
    "changeRequestStatus",
    "editRequest",
    "deleteRequest",
    "requestCancellation",
    "confirmReceipt",
]);
async function executeRequestAction(c, user, actor, a) {
    const actorId = Number(actor.id);
    if (a.type === "createRequests") {
        (0, permissions_1.demand)(user, "request");
        if (!Array.isArray(a.entries) ||
            !a.entries.length ||
            a.entries.length > 30 ||
            a.entries.some((e) => !e || typeof e !== "object"))
            throw new permissions_1.ActionError("Carrinho inválido.");
        const entries = a.entries;
        const requestKey = a.requestKey;
        if (requestKey !== undefined) {
            if (typeof requestKey !== "string" ||
                !/^[a-zA-Z0-9_-]{16,64}$/.test(requestKey))
                throw new permissions_1.ActionError("Identificador de envio inválido.");
            const hash = (0, node_crypto_1.createHash)("sha256")
                .update(JSON.stringify(entries))
                .digest("hex");
            await c.execute("INSERT IGNORE INTO request_submissions(actor_id,request_key,payload_hash) VALUES(?,?,?)", [actorId, requestKey, hash]);
            const submitted = await (0, stock_ledger_1.first)(c, "SELECT payload_hash,result FROM request_submissions WHERE actor_id=? AND request_key=? FOR UPDATE", [actorId, requestKey]);
            if (submitted.payload_hash !== hash)
                throw new permissions_1.ActionError("Este envio já pertence a outro carrinho.", 409);
            if (submitted.result)
                return typeof submitted.result === "string"
                    ? JSON.parse(submitted.result)
                    : submitted.result;
        }
        if (new Set(entries.map((e) => (0, permissions_1.text)(e.code, 64).toUpperCase())).size !==
            entries.length)
            throw new permissions_1.ActionError("Agrupe os itens repetidos no carrinho.");
        const batch = (0, node_crypto_1.randomUUID)(), ids = [];
        for (const e of [...entries].sort((x, y) => String(x.code).localeCompare(String(y.code)))) {
            const p = await (0, stock_ledger_1.partLock)(c, e.code), q = (0, permissions_1.integer)(e.quantity);
            if (!["Leve", "Moderado", "Urgente"].includes(String(e.priority)))
                throw new permissions_1.ActionError("Urgência inválida.");
            if ((q > 10 || e.priority === "Urgente") && !(0, permissions_1.text)(e.justification))
                throw new permissions_1.ActionError("Justifique o pedido fora do padrão.");
            if (q >
                (await (0, stock_ledger_1.stock)(c, Number(p.id))).reduce((sum, r) => sum + (0, stock_ledger_1.available)(r), 0))
                throw new permissions_1.ActionError("Saldo disponível insuficiente.", 409);
            const [r] = await c.execute("INSERT INTO requests(requester_id,block_id,part_id,quantity,priority,justification,batch_id,sector) VALUES(?,?,?,?,?,?,?,?)", [
                actorId,
                actor.block_id,
                p.id,
                q,
                e.priority,
                (0, permissions_1.text)(e.justification) || null,
                batch,
                actor.sector,
            ]);
            ids.push(r.insertId);
            await (0, stock_ledger_1.audit)(c, actorId, "request", r.insertId, "create", {
                quantity: q,
                batch,
            });
        }
        const result = { ids, batch };
        if (requestKey)
            await c.execute("UPDATE request_submissions SET result=? WHERE actor_id=? AND request_key=?", [JSON.stringify(result), actorId, requestKey]);
        return result;
    }
    const id = (0, permissions_1.integer)(a.id), lookup = await (0, stock_ledger_1.first)(c, "SELECT part_id FROM requests WHERE id=?", [id]);
    if (!lookup)
        throw new permissions_1.ActionError("Requisição não encontrada.", 404);
    // Toda mutação de estoque começa pelo lock da peça; carrinhos ordenam os locks.
    const p = await (0, stock_ledger_1.partLock)(c, null, lookup.part_id), r = await (0, stock_ledger_1.first)(c, "SELECT * FROM requests WHERE id=? FOR UPDATE", [id]);
    const owns = Number(r.requester_id) === actorId;
    if ((user.role === "funcionario" && !owns) ||
        (user.role === "lider" && Number(r.block_id) !== Number(actor.block_id)))
        throw new permissions_1.ActionError("Requisição fora do seu escopo.", 403);
    const pending = ["Pendente", "Em análise"].includes(String(r.status));
    if (a.type === "editRequest" || a.type === "deleteRequest") {
        (0, permissions_1.demand)(user, "request");
        if (!owns || !pending)
            throw new permissions_1.ActionError("Somente o requisitor pode editar/excluir antes da aprovação.", 403);
        if (a.type === "editRequest") {
            const q = (0, permissions_1.integer)(a.quantity);
            if (q > (await (0, stock_ledger_1.stock)(c, Number(p.id))).reduce((s, v) => s + (0, stock_ledger_1.available)(v), 0))
                throw new permissions_1.ActionError("Saldo insuficiente.", 409);
            await c.execute("UPDATE requests SET quantity=? WHERE id=?", [q, id]);
        }
        else
            await c.execute("UPDATE requests SET status='Cancelada',cancellation_reason='Excluída pelo requisitor antes da aprovação' WHERE id=?", [id]);
    }
    else if (a.type === "confirmReceipt") {
        if (!owns || r.status !== "Entregue" || r.received_at)
            throw new permissions_1.ActionError("Recebimento indisponível nesta etapa.", 409);
        await c.execute("UPDATE requests SET received_at=UTC_TIMESTAMP(3) WHERE id=?", [id]);
    }
    else if (a.type === "requestCancellation") {
        if (!owns || r.status !== "Aprovada")
            throw new permissions_1.ActionError("Cancelamento só pode ser solicitado após aprovação e antes da entrega.", 409);
        await c.execute("UPDATE requests SET status='Cancelamento solicitado',cancellation_reason=? WHERE id=?", [(0, permissions_1.reason)(a.reason), id]);
    }
    else {
        const next = String(a.status);
        if (user.role === "funcionario")
            throw new permissions_1.ActionError("Aprovação/entrega exige outro perfil.", 403);
        if (next === "Em análise" && r.status === "Pendente") {
            (0, permissions_1.demand)(user, "approve", "requests.analyze");
            await c.execute("UPDATE requests SET status='Em análise' WHERE id=?", [
                id,
            ]);
        }
        else if (next === "Aprovada" && (pending || r.status === "Aprovada")) {
            (0, permissions_1.demand)(user, "approve");
            const locations = await (0, stock_ledger_1.stock)(c, Number(p.id));
            const published = await (0, stock_ledger_1.first)(c, "SELECT graph FROM map_versions WHERE status='Publicada'");
            const graph = published
                ? (typeof published.graph === "string"
                    ? JSON.parse(published.graph)
                    : published.graph)
                : null;
            const destination = graph?.nodes.find((n) => n.blockId === Number(r.block_id) &&
                (n.kind === "delivery" || n.kind === "block"));
            const ranked = locations
                .map((l) => {
                const node = graph?.nodes.find((n) => n.id === l.map_node_id) ??
                    graph?.nodes.find((n) => n.warehouseId === Number(l.warehouse_id));
                const path = graph && node && destination
                    ? (0, routing_1.shortestPath)(graph, node.id, destination.id)
                    : null;
                return {
                    l,
                    score: graph?.reviewed && path ? path.cost : Infinity,
                };
            })
                .sort((a, b) => a.score - b.score || Number(b.l.block_id === r.block_id) - Number(a.l.block_id === r.block_id) || (0, stock_ledger_1.available)(b.l) - (0, stock_ledger_1.available)(a.l));
            const existing = await (0, stock_ledger_1.rows)(c, "SELECT warehouse_id,quantity FROM request_reservations WHERE request_id=? FOR UPDATE", [id]);
            let remaining = Number(r.quantity) -
                existing.reduce((sum, v) => sum + Number(v.quantity), 0);
            for (const { l } of ranked) {
                const q = Math.min(remaining, (0, stock_ledger_1.available)(l));
                if (q > 0) {
                    await c.execute("INSERT INTO request_reservations(request_id,part_id,warehouse_id,quantity) VALUES(?,?,?,?) ON DUPLICATE KEY UPDATE quantity=quantity+VALUES(quantity)", [id, p.id, l.warehouse_id, q]);
                    remaining -= q;
                }
            }
            if (remaining)
                throw new permissions_1.ActionError("Saldo insuficiente para reservar. Nenhuma aprovação foi aplicada.", 409);
            await c.execute("UPDATE requests SET status='Aprovada',approved_by=?,approved_at=COALESCE(approved_at,UTC_TIMESTAMP(3)) WHERE id=?", [actorId, id]);
        }
        else if (next === "Cancelada" &&
            [
                "Pendente",
                "Em análise",
                "Aprovada",
                "Cancelamento solicitado",
            ].includes(String(r.status))) {
            if (user.role === "almoxarifado" &&
                !["Aprovada", "Cancelamento solicitado"].includes(String(r.status)))
                throw new permissions_1.ActionError("Aguardando aprovação do gestor.", 403);
            await c.execute("DELETE FROM request_reservations WHERE request_id=?", [
                id,
            ]);
            await c.execute("UPDATE requests SET status='Cancelada',cancellation_reason=COALESCE(cancellation_reason,?) WHERE id=?", [(0, permissions_1.reason)(a.reason ?? "Cancelamento confirmado pelo responsável"), id]);
        }
        else if (next === "Entregue" && r.status === "Aprovada") {
            (0, permissions_1.demand)(user, "stock");
            (0, permissions_1.demand)(user, "stock", "requests.deliver");
            (0, stock_ledger_1.scan)(p, a.qrCode);
            if ((0, permissions_1.integer)(a.confirmedQuantity) !== Number(r.quantity))
                throw new permissions_1.ActionError("Confirme a quantidade exata separada.", 422);
            // Capture the current publication at delivery as well; earlier departures
            // remain in history and do not certify that their path was travelled.
            await (0, delivery_planning_1.recordDeliveryPlan)(c, user, { action: "planDelivery", atDelivery: true }, id);
            const reserved = await (0, stock_ledger_1.rows)(c, "SELECT * FROM request_reservations WHERE request_id=? ORDER BY warehouse_id FOR UPDATE", [id]);
            if (reserved.reduce((s, v) => s + Number(v.quantity), 0) !==
                Number(r.quantity))
                throw new permissions_1.ActionError("Reserva incompleta. Peça revalidação ao gestor.", 409);
            for (const v of reserved) {
                const [updated] = await c.execute("UPDATE inventory SET quantity=quantity-? WHERE part_id=? AND warehouse_id=? AND quantity>=?", [v.quantity, p.id, v.warehouse_id, v.quantity]);
                if (updated.affectedRows !== 1)
                    throw new permissions_1.ActionError("Saldo inconsistente. Entrega bloqueada.", 409);
                await (0, stock_ledger_1.movement)(c, actorId, Number(p.id), Number(v.warehouse_id), "saida", Number(v.quantity), "Entrega conferida", id, Number(r.block_id));
            }
            await c.execute("DELETE FROM request_reservations WHERE request_id=?", [
                id,
            ]);
            await c.execute("UPDATE requests SET status='Entregue',fulfilled_by=?,fulfilled_from=?,delivered_at=UTC_TIMESTAMP(3) WHERE id=?", [actorId, reserved[0].warehouse_id, id]);
        }
        else
            throw new permissions_1.ActionError("Transição de estado inválida.", 409);
    }
    await (0, stock_ledger_1.audit)(c, actorId, "request", id, String(a.type), {
        status: a.status ?? null,
        quantity: a.quantity ?? null,
    });
    return { id };
}
