// Generated by scripts/sync-workspace.mjs from lib/stock-ledger.ts.
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.available = exports.first = void 0;
exports.rows = rows;
exports.insert = insert;
exports.audit = audit;
exports.movement = movement;
exports.stock = stock;
exports.partLock = partLock;
exports.place = place;
exports.scan = scan;
exports.capacity = capacity;
const permissions_1 = require("./permissions");
async function rows(c, sql, args = []) {
    const [r] = await c.execute(sql, args);
    return r;
}
const first = async (c, sql, args = []) => (await rows(c, sql, args))[0];
exports.first = first;
async function insert(c, sql, args) {
    const [result] = await c.execute(sql, args);
    return { id: result.insertId };
}
async function audit(c, actor, entity, id, event, data) {
    await c.execute("INSERT INTO audit_log(actor_id,entity_type,entity_id,action,details) VALUES(?,?,?,?,?)", [actor, entity, id, event, JSON.stringify(data)]);
}
async function movement(c, actor, part, warehouse, kind, quantity, note, request = null, block = null, returned = null, transfer = null) {
    if (quantity)
        await c.execute("INSERT INTO stock_movements(part_id,warehouse_id,kind,quantity,actor_id,reason,request_id,block_id,return_id,transfer_id) VALUES(?,?,?,?,?,?,?,?,?,?)", [
            part,
            warehouse,
            kind,
            quantity,
            actor,
            note,
            request,
            block,
            returned,
            transfer,
        ]);
}
async function stock(c, part) {
    const balances = await rows(c, "SELECT i.*, w.name, w.block_id, w.is_central FROM inventory i JOIN warehouses w ON w.id=i.warehouse_id WHERE i.part_id=? AND w.active=TRUE ORDER BY i.warehouse_id FOR UPDATE", [part]);
    // Locking reads see the latest committed reservations even under REPEATABLE READ.
    const reservations = await rows(c, "SELECT warehouse_id,quantity FROM request_reservations WHERE part_id=? FOR UPDATE", [part]);
    const pending = await rows(c, "SELECT id,source_warehouse_id,quantity FROM stock_transfers WHERE part_id=? AND status='Solicitada' ORDER BY id FOR UPDATE", [part]);
    return balances.map((b) => ({
        ...b,
        reserved: reservations
            .filter((r) => Number(r.warehouse_id) === Number(b.warehouse_id))
            .reduce((sum, r) => sum + Number(r.quantity), 0),
        pending_outgoing: pending.filter((t) => Number(t.source_warehouse_id) === Number(b.warehouse_id)).reduce((sum, t) => sum + Number(t.quantity), 0),
    }));
}
const available = (r) => Number(r.quantity) - Number(r.reserved) - Number(r.pending_outgoing ?? 0);
exports.available = available;
async function partLock(c, code, id) {
    const p = await (0, exports.first)(c, `SELECT * FROM parts WHERE ${id ? "id" : "code"}=? AND active=TRUE FOR UPDATE`, [id ?? (0, permissions_1.text)(code, 64)]);
    if (!p)
        throw new permissions_1.ActionError("Peça não encontrada.", 404);
    return p;
}
async function place(c, value) {
    const w = await (0, exports.first)(c, "SELECT * FROM warehouses WHERE name=? AND active=TRUE", [(0, permissions_1.text)(value, 80)]);
    if (!w)
        throw new permissions_1.ActionError("Almoxarifado inválido.");
    return w;
}
function scan(p, code) {
    if (![p.code, p.qr_code].some((v) => typeof code === "string" && String(v) === code))
        throw new permissions_1.ActionError("Código lido não corresponde à peça.", 422);
}
function capacity(row, quantity) {
    if (row.capacity !== null &&
        row.capacity !== undefined &&
        quantity > Number(row.capacity))
        throw new permissions_1.ActionError("Capacidade do local excedida.", 409);
}
