import type { Config } from "@vladmandic/human";
export const faceModelConfig: Partial<Config> = {
  backend: "webgl",
  modelBasePath: "/models/human/",
  cacheModels: false,
  debug: false,
  warmup: "none",
  cacheSensitivity: 0,
  skipAllowed: false,
  filter: { enabled: false, return: false },
  face: {
    enabled: true,
    detector: {
      maxDetected: 3,
      minConfidence: 0.6,
      rotation: true,
      return: false,
      skipFrames: 0,
      skipTime: 0,
    },
    mesh: { enabled: true },
    description: { enabled: true, skipFrames: 0, skipTime: 0 },
    iris: { enabled: false },
    emotion: { enabled: false },
    antispoof: { enabled: false },
    liveness: { enabled: false },
  },
  body: { enabled: false },
  hand: { enabled: false },
  object: { enabled: false },
  gesture: { enabled: false },
  segmentation: { enabled: false },
};
