// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/admin" | "/admin/all-requests" | "/admin/create" | "/admin/create/new" | "/admin/dashboard" | "/admin/dashboard/block" | "/admin/dashboard/by-part" | "/admin/dashboard/parts" | "/admin/dashboard/parts/[id]" | "/admin/dashboard/sector/[id]" | "/admin/dashboard/stock" | "/admin/dashboard/stock/[part]/[id]" | "/admin/dashboard/warehouse" | "/admin/history" | "/admin/history/export" | "/admin/map" | "/admin/purchases" | "/admin/recommendations" | "/catalogo" | "/catalogo/item/[id]" | "/department-head" | "/department-head/dashboard" | "/department-head/history" | "/department-head/materials" | "/department-head/requests" | "/employee" | "/employee/history" | "/employee/request" | "/employee/request/[part]/[id]" | "/inicio/[perfil]" | "/login" | "/profile" | "/warehouse" | "/warehouse/dashboard" | "/warehouse/dashboard/by-part" | "/warehouse/dashboard/parts" | "/warehouse/history" | "/warehouse/purchases" | "/warehouse/recommendations" | "/warehouse/requests" | "/warehouse/returns" | "/warehouse/stock/[part]/[id]"
type AppRouteHandlerRoutes = "/api/industrial-links" | "/api/items" | "/api/items/[id]" | "/api/items/import" | "/api/items/resolve" | "/api/james/chat" | "/api/james/voice" | "/api/login" | "/api/login/face" | "/api/logout" | "/api/maps" | "/api/operations" | "/api/parts-consumption" | "/api/profile" | "/api/requisicoes" | "/api/workspace" | "/health"
type PageRoutes = never
type LayoutRoutes = "/" | "/admin" | "/catalogo" | "/department-head" | "/employee" | "/warehouse"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/admin": {}
  "/admin/all-requests": {}
  "/admin/create": {}
  "/admin/create/new": {}
  "/admin/dashboard": {}
  "/admin/dashboard/block": {}
  "/admin/dashboard/by-part": {}
  "/admin/dashboard/parts": {}
  "/admin/dashboard/parts/[id]": { "id": string; }
  "/admin/dashboard/sector/[id]": { "id": string; }
  "/admin/dashboard/stock": {}
  "/admin/dashboard/stock/[part]/[id]": { "part": string; "id": string; }
  "/admin/dashboard/warehouse": {}
  "/admin/history": {}
  "/admin/history/export": {}
  "/admin/map": {}
  "/admin/purchases": {}
  "/admin/recommendations": {}
  "/api/industrial-links": {}
  "/api/items": {}
  "/api/items/[id]": { "id": string; }
  "/api/items/import": {}
  "/api/items/resolve": {}
  "/api/james/chat": {}
  "/api/james/voice": {}
  "/api/login": {}
  "/api/login/face": {}
  "/api/logout": {}
  "/api/maps": {}
  "/api/operations": {}
  "/api/parts-consumption": {}
  "/api/profile": {}
  "/api/requisicoes": {}
  "/api/workspace": {}
  "/catalogo": {}
  "/catalogo/item/[id]": { "id": string; }
  "/department-head": {}
  "/department-head/dashboard": {}
  "/department-head/history": {}
  "/department-head/materials": {}
  "/department-head/requests": {}
  "/employee": {}
  "/employee/history": {}
  "/employee/request": {}
  "/employee/request/[part]/[id]": { "part": string; "id": string; }
  "/health": {}
  "/inicio/[perfil]": { "perfil": string; }
  "/login": {}
  "/profile": {}
  "/warehouse": {}
  "/warehouse/dashboard": {}
  "/warehouse/dashboard/by-part": {}
  "/warehouse/dashboard/parts": {}
  "/warehouse/history": {}
  "/warehouse/purchases": {}
  "/warehouse/recommendations": {}
  "/warehouse/requests": {}
  "/warehouse/returns": {}
  "/warehouse/stock/[part]/[id]": { "part": string; "id": string; }
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/admin": never
  "/catalogo": never
  "/department-head": never
  "/employee": never
  "/warehouse": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
