// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../../app/admin/all-requests/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/all-requests">> = Specific
  const handler = {} as typeof import("../../../app/admin/all-requests/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/create/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/create/new">> = Specific
  const handler = {} as typeof import("../../../app/admin/create/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/create/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/create">> = Specific
  const handler = {} as typeof import("../../../app/admin/create/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/dashboard/block/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/dashboard/block">> = Specific
  const handler = {} as typeof import("../../../app/admin/dashboard/block/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/dashboard/by-part/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/dashboard/by-part">> = Specific
  const handler = {} as typeof import("../../../app/admin/dashboard/by-part/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/dashboard">> = Specific
  const handler = {} as typeof import("../../../app/admin/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/dashboard/parts/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/dashboard/parts/[id]">> = Specific
  const handler = {} as typeof import("../../../app/admin/dashboard/parts/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/dashboard/parts/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/dashboard/parts">> = Specific
  const handler = {} as typeof import("../../../app/admin/dashboard/parts/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/dashboard/sector/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/dashboard/sector/[id]">> = Specific
  const handler = {} as typeof import("../../../app/admin/dashboard/sector/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/dashboard/stock/[part]/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/dashboard/stock/[part]/[id]">> = Specific
  const handler = {} as typeof import("../../../app/admin/dashboard/stock/[part]/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/dashboard/stock/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/dashboard/stock">> = Specific
  const handler = {} as typeof import("../../../app/admin/dashboard/stock/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/dashboard/warehouse/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/dashboard/warehouse">> = Specific
  const handler = {} as typeof import("../../../app/admin/dashboard/warehouse/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/history/export/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/history/export">> = Specific
  const handler = {} as typeof import("../../../app/admin/history/export/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/history/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/history">> = Specific
  const handler = {} as typeof import("../../../app/admin/history/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/map/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/map">> = Specific
  const handler = {} as typeof import("../../../app/admin/map/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../../app/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/purchases/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/purchases">> = Specific
  const handler = {} as typeof import("../../../app/admin/purchases/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/admin/recommendations/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/recommendations">> = Specific
  const handler = {} as typeof import("../../../app/admin/recommendations/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/catalogo/item/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/catalogo/item/[id]">> = Specific
  const handler = {} as typeof import("../../../app/catalogo/item/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/catalogo/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/catalogo">> = Specific
  const handler = {} as typeof import("../../../app/catalogo/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/department-head/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/department-head/dashboard">> = Specific
  const handler = {} as typeof import("../../../app/department-head/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/department-head/history/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/department-head/history">> = Specific
  const handler = {} as typeof import("../../../app/department-head/history/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/department-head/materials/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/department-head/materials">> = Specific
  const handler = {} as typeof import("../../../app/department-head/materials/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/department-head/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/department-head">> = Specific
  const handler = {} as typeof import("../../../app/department-head/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/department-head/requests/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/department-head/requests">> = Specific
  const handler = {} as typeof import("../../../app/department-head/requests/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/employee/history/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/employee/history">> = Specific
  const handler = {} as typeof import("../../../app/employee/history/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/employee/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/employee">> = Specific
  const handler = {} as typeof import("../../../app/employee/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/employee/request/[part]/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/employee/request/[part]/[id]">> = Specific
  const handler = {} as typeof import("../../../app/employee/request/[part]/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/employee/request/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/employee/request">> = Specific
  const handler = {} as typeof import("../../../app/employee/request/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/inicio/[perfil]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/inicio/[perfil]">> = Specific
  const handler = {} as typeof import("../../../app/inicio/[perfil]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../../app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/profile/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/profile">> = Specific
  const handler = {} as typeof import("../../../app/profile/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/warehouse/dashboard/by-part/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/warehouse/dashboard/by-part">> = Specific
  const handler = {} as typeof import("../../../app/warehouse/dashboard/by-part/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/warehouse/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/warehouse/dashboard">> = Specific
  const handler = {} as typeof import("../../../app/warehouse/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/warehouse/dashboard/parts/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/warehouse/dashboard/parts">> = Specific
  const handler = {} as typeof import("../../../app/warehouse/dashboard/parts/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/warehouse/history/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/warehouse/history">> = Specific
  const handler = {} as typeof import("../../../app/warehouse/history/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/warehouse/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/warehouse">> = Specific
  const handler = {} as typeof import("../../../app/warehouse/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/warehouse/purchases/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/warehouse/purchases">> = Specific
  const handler = {} as typeof import("../../../app/warehouse/purchases/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/warehouse/recommendations/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/warehouse/recommendations">> = Specific
  const handler = {} as typeof import("../../../app/warehouse/recommendations/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/warehouse/requests/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/warehouse/requests">> = Specific
  const handler = {} as typeof import("../../../app/warehouse/requests/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/warehouse/returns/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/warehouse/returns">> = Specific
  const handler = {} as typeof import("../../../app/warehouse/returns/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/warehouse/stock/[part]/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/warehouse/stock/[part]/[id]">> = Specific
  const handler = {} as typeof import("../../../app/warehouse/stock/[part]/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/industrial-links/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/industrial-links">> = Specific
  const handler = {} as typeof import("../../../app/api/industrial-links/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/items/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/items/[id]">> = Specific
  const handler = {} as typeof import("../../../app/api/items/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/items/import/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/items/import">> = Specific
  const handler = {} as typeof import("../../../app/api/items/import/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/items/resolve/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/items/resolve">> = Specific
  const handler = {} as typeof import("../../../app/api/items/resolve/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/items/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/items">> = Specific
  const handler = {} as typeof import("../../../app/api/items/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/james/chat/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/james/chat">> = Specific
  const handler = {} as typeof import("../../../app/api/james/chat/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/james/voice/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/james/voice">> = Specific
  const handler = {} as typeof import("../../../app/api/james/voice/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/login/face/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/login/face">> = Specific
  const handler = {} as typeof import("../../../app/api/login/face/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/login/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/login">> = Specific
  const handler = {} as typeof import("../../../app/api/login/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/logout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/logout">> = Specific
  const handler = {} as typeof import("../../../app/api/logout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/maps/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/maps">> = Specific
  const handler = {} as typeof import("../../../app/api/maps/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/operations/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/operations">> = Specific
  const handler = {} as typeof import("../../../app/api/operations/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/parts-consumption/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/parts-consumption">> = Specific
  const handler = {} as typeof import("../../../app/api/parts-consumption/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/profile/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/profile">> = Specific
  const handler = {} as typeof import("../../../app/api/profile/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/requisicoes/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/requisicoes">> = Specific
  const handler = {} as typeof import("../../../app/api/requisicoes/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/workspace/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/workspace">> = Specific
  const handler = {} as typeof import("../../../app/api/workspace/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/health/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/health">> = Specific
  const handler = {} as typeof import("../../../app/health/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../../app/admin/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../../app/admin/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/catalogo/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/catalogo">> = Specific
  const handler = {} as typeof import("../../../app/catalogo/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/department-head/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/department-head">> = Specific
  const handler = {} as typeof import("../../../app/department-head/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/employee/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/employee">> = Specific
  const handler = {} as typeof import("../../../app/employee/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/warehouse/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/warehouse">> = Specific
  const handler = {} as typeof import("../../../app/warehouse/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
